<div class="show pt-2 pb-3 shadow">
    <div class="grid-container ps-3 py-2 pe-3">
            <div class="grid-item">A</div>
            <div class="grid-item">B</div>
            <div class="grid-item">C</div>
            <div class="grid-item">D</div>
            <div class="grid-item">E</div>
            <div class="grid-item">F</div>
            <div class="grid-item">G</div>
            <div class="grid-item">H</div>
            <div class="grid-item">I</div>
            <div class="grid-item">J</div>
            <div class="grid-item">K</div>
            <div class="grid-item">L</div>
            <div class="grid-item">M</div>
            <div class="grid-item">N</div>
            <div class="grid-item">O</div>
            <div class="grid-item">P</div>
            <div class="grid-item">Q</div>
            <div class="grid-item">R</div>
            <div class="grid-item">S</div>
            <div class="grid-item">T</div>
            <div class="grid-item">U</div>
            <div class="grid-item">V</div>
            <div class="grid-item">w</div>
            <div class="grid-item">X</div>
            <div class="grid-item">Y</div>
            <div class="grid-items">Z</div>
    </div>
</div>